import React from "react";
import "../pages/FallnikAIPage.css";
import { FaDownload } from "react-icons/fa";

const SummarySection = ({ summary, downloadUrl}) => {
    return (
        <div className="summary-section">
            <h3>Summary</h3>
            <div className="summary-content">{summary}</div>
            {downloadUrl && (
                <div className="download-link">
                    <h3>You can download the summary i just generated by using this button.</h3>
                    <a href={downloadUrl} target="_blank" rel="noopener noreferrer" download>
                        <FaDownload style={{marginRight: "8px"}} />
                        Download.
                    </a>
                </div>
            )}
        </div>
    );
};

export default SummarySection;